import type { editor } from "monaco-editor";

/** VS Code–style token colors tuned for BulkFirePro's dark zinc UI. */
export const BULKFIRE_MONACO_THEME = "bulkfire-dark";

export const bulkfireMonacoTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "tag", foreground: "569CD6" },
    { token: "tag.html", foreground: "569CD6" },
    { token: "metatag", foreground: "569CD6" },
    { token: "metatag.html", foreground: "C586C0" },
    { token: "metatag.content.html", foreground: "808080" },
    { token: "attribute.name", foreground: "CE9178" },
    { token: "attribute.name.html", foreground: "CE9178" },
    { token: "attribute.value", foreground: "B5CEA8" },
    { token: "attribute.value.html", foreground: "B5CEA8" },
    { token: "string", foreground: "B5CEA8" },
    { token: "string.html", foreground: "B5CEA8" },
    { token: "comment", foreground: "6A9955", fontStyle: "italic" },
    { token: "comment.block.html", foreground: "6A9955", fontStyle: "italic" },
    { token: "delimiter", foreground: "808080" },
    { token: "delimiter.html", foreground: "808080" },
    { token: "keyword", foreground: "C586C0" },
    { token: "keyword.css", foreground: "C586C0" },
    { token: "attribute.name.css", foreground: "C586C0" },
    { token: "attribute.value.number.css", foreground: "4EC9B0" },
    { token: "attribute.value.unit.css", foreground: "4EC9B0" },
    { token: "attribute.value.hex.css", foreground: "4EC9B0" },
    { token: "number", foreground: "4EC9B0" },
    { token: "number.float", foreground: "4EC9B0" },
    { token: "number.hex", foreground: "4EC9B0" },
    { token: "variable", foreground: "9CDCFE" },
    { token: "variable.predefined", foreground: "4EC9B0" },
  ],
  colors: {
    "editor.background": "#09090b",
    "editor.foreground": "#e4e4e7",
    "editorLineNumber.foreground": "#52525b",
    "editorLineNumber.activeForeground": "#d4d4d8",
    "editor.lineHighlightBackground": "#18181b",
    "editor.lineHighlightBorder": "#27272a",
    "editor.selectionBackground": "#065f4640",
    "editor.inactiveSelectionBackground": "#065f4626",
    "editor.selectionHighlightBackground": "#065f4626",
    "editorCursor.foreground": "#fafafa",
    "editorWidget.background": "#18181b",
    "editorWidget.border": "#3f3f46",
    "editorSuggestWidget.background": "#18181b",
    "editorSuggestWidget.border": "#3f3f46",
    "editorSuggestWidget.selectedBackground": "#065f4640",
    "editorHoverWidget.background": "#18181b",
    "editorHoverWidget.border": "#3f3f46",
    "editorIndentGuide.background1": "#27272a",
    "editorIndentGuide.activeBackground1": "#3f3f46",
    "editorBracketMatch.background": "#065f4633",
    "editorBracketMatch.border": "#10b98166",
    "minimap.background": "#09090b",
    "scrollbarSlider.background": "#3f3f4666",
    "scrollbarSlider.hoverBackground": "#52525b99",
    "scrollbarSlider.activeBackground": "#71717a99",
    "focusBorder": "#10b98166",
  },
};
